# Generated by Django 5.1.1 on 2024-10-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GlobalsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Kmeans_file_name",
                    models.CharField(
                        default="Kmeans_model_default.joblib", max_length=255
                    ),
                ),
                (
                    "Word2vec_file_name",
                    models.CharField(
                        default="word2vecmodel_default.joblib", max_length=255
                    ),
                ),
            ],
        ),
    ]
